# Generated by Django 2.0.6 on 2018-07-17 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateTimeField(verbose_name='Lesson Date')),
                ('teacher', models.CharField(default=None, max_length=20)),
                ('present', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='lesson_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='present',
        ),
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Student'),
        ),
    ]
